// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpsXUsiGkoWjWZjLYjHQp8zvm2xugQHxg',
    appId: '1:73192084322:web:4f26d96e0ba406a061d23b',
    messagingSenderId: '73192084322',
    projectId: 'hms-db-6db29',
    authDomain: 'hms-db-6db29.firebaseapp.com',
    storageBucket: 'hms-db-6db29.firebasestorage.app',
    measurementId: 'G-9GDHVPYNCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZZTXvqRZFWUrWNEb4r8HQWYkMpQ1yQeo',
    appId: '1:73192084322:android:8bba7e1ef9a6044461d23b',
    messagingSenderId: '73192084322',
    projectId: 'hms-db-6db29',
    storageBucket: 'hms-db-6db29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWMNNiXhe8k0yYK9FfgFcyjzj0VOr2gRU',
    appId: '1:73192084322:ios:a0135ed27363f4a861d23b',
    messagingSenderId: '73192084322',
    projectId: 'hms-db-6db29',
    storageBucket: 'hms-db-6db29.firebasestorage.app',
    iosBundleId: 'com.example.androidHms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWMNNiXhe8k0yYK9FfgFcyjzj0VOr2gRU',
    appId: '1:73192084322:ios:a0135ed27363f4a861d23b',
    messagingSenderId: '73192084322',
    projectId: 'hms-db-6db29',
    storageBucket: 'hms-db-6db29.firebasestorage.app',
    iosBundleId: 'com.example.androidHms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpsXUsiGkoWjWZjLYjHQp8zvm2xugQHxg',
    appId: '1:73192084322:web:dbfac08c3b02c5c161d23b',
    messagingSenderId: '73192084322',
    projectId: 'hms-db-6db29',
    authDomain: 'hms-db-6db29.firebaseapp.com',
    storageBucket: 'hms-db-6db29.firebasestorage.app',
    measurementId: 'G-VDXFW75JTB',
  );
}
